# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: YunwooPCEngineering.Hub
PackageVersion: 0.1.18
DefaultLocale: ko-KR
ManifestType: version
ManifestVersion: 1.5.0
